### ISSUE TITLE
sku can be skuCount

### ISSUE THREAD

**Issue by ConsenSys-Academy** [dev-bootcamp-2019/supply-chain-cspannos#1]
https://github.com/dev-bootcamp-2019/supply-chain-cspannos/blob/413e1e959c358e13acff951c897269a053409550/contracts/SupplyChain.sol#L103

The item sku attribute can be set to the skuCount state variable, you shouldn't have to pass it into the function as a parameter.

**Comment by cspannos** [comment]
Got it. Thank you.
