### ISSUE TITLE
emit event before incrementing the sku

### ISSUE THREAD

**Issue by ConsenSys-Academy** [dev-bootcamp-2019/supply-chain-cspannos#2]
https://github.com/dev-bootcamp-2019/supply-chain-cspannos/blob/413e1e959c358e13acff951c897269a053409550/contracts/SupplyChain.sol#L105

You should emit the event in the `addItem` function before the skuCount is incremented, so that the event has the same sku as the added item

**Comment by cspannos** [comment]
Okay, that makes sense. Thank you. Just pushed an update. Cheers!
